import Head from "next/head";
import Image from "next/image";
import { Header, Nav, Results } from "../components";
import request from "../utils/request";

export default function Home({ results }) {
  return (
    <div>
      <Head>
        <title>Hulu 1.0</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <Nav />
      <Results results={results} />
    </div>
  );
}

export async function getServerSideProps(context) {
  const genre = context.query.genre;

  const req = await fetch(
    `https://api.themoviedb.org/3${request[genre]?.url || request[0].url}`
  ).then((res) => res.json());

  return {
    props: {
      results: req.results,
    },
  };
}
